### ISSUE TITLE
Playing a sound causes an error.

### ISSUE THREAD

**Issue by hmlyn523** [flame-engine/flame#1038]
Playing a sound causes an error.

# Current bug behaviour
If the sound is played too many times, an error will occur.

# Expected behaviour
Avoiding errors.

# Steps to reproduce
If you use FlameAudio.play() and play a sound too many times, you will get an error.
For some reason, I get an unsupported error.

Error: NotSupportedError: Failed to load because no supported source was found.

Since the example does not work, it is possible that the usage is incorrect.

# Flutter doctor output
```
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale ja-JP)
    • Flutter version 2.5.2 at /Users/tatsuya/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (3 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tatsuya/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

# More environment information
* flame: ^1.0.0-releasecandidate.15
* flame_forge2d: ^0.8.2-releasecandidate.15
* flame_splash_screen: ^0.1.0
* flame_audio: ^1.0.0-rc.15
* Platform affected: ios, web
* Platform version affected: ios 15.0.0, Chrome 92.0.4515.107

# Log information
```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://127.0.0.1:58494/fznNvyUqH1o=/ws
Debug service listening on ws://127.0.0.1:58494/fznNvyUqH1o=/ws

💪 Running with sound null safety 💪
Debug service listening on ws://127.0.0.1:58494/fznNvyUqH1o=/ws
Error: NotSupportedError: Failed to load because no supported source was found.


    at Object.createErrorWithStack (http://localhost:58450/dart_sdk.js:5074:12)
    at Object._rethrow (http://localhost:58450/dart_sdk.js:38925:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:58450/dart_sdk.js:38921:13)
    at Object._microtaskLoop (http://localhost:58450/dart_sdk.js:38778:13)
    at _startMicrotaskLoop (http://localhost:58450/dart_sdk.js:38784:13)
    at http://localhost:58450/dart_sdk.js:34519:9
```

# More information
None in particular

**Comment by tatsuya-sagara** [comment]
@erickzanardo -san
Since it was closed, no one may see this result report, but I'll report it just in case.

When I used FlameAudio.play(), the error occurred after about 50 times, but when I used AudioPool, it was fine even after 200 times or more.

I am wondering when FlameAudio.play() should be used in the first place. (Is it in the documentation?)
