### ISSUE TITLE
Small sample game error!?

### ISSUE THREAD

**Issue by YohanWadia** [flame-engine/flame#1269]
# Current bug behaviour
I am not able to run the example at https://github.com/flame-engine/flame/tree/main/packages/flame/example
I get an error in the logs... and a red screen on the device/emulator/chrome

# Expected behaviour

# Steps to reproduce

# Flutter doctor output

```
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19043.1415], locale en-US)
    • Flutter version 2.5.3 at C:\flutterio\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (10 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Yo\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\Yo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 96.0.4664.110
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.52


```

# More environment information
* Flame version: 1.0.0
* Platform affected: android, web
* Platform version Tested on: android 9 emulator, chrome, and One+1 device 

# Log information

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building GameWidget<MyGame>(dirty, state: _GameWidgetState<MyGame>#d13eb):
        WARNING: Both Advanced and Basic detectors detected.
        Advanced detectors will override basic detectors and the later will not receive events
'package:flame/src/game/game_widget/game_widget.dart':
Failed assertion: line 273 pos 7: '!(hasBasicDetectors && hasAdvancedDetectors)'

The relevant error-causing widget was: 
  GameWidget<MyGame> GameWidget:file:///D:/Users/Yo/AndroidStudioProjects/FlutterStuff/FlameV1.0/flutter_app/lib/main.dart:11:5
When the exception was thrown, this was the stack: 
#2      _GameWidgetState.build (package:flame/src/game/game_widget/game_widget.dart:273:7)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4782:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4665:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831:11)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638:5)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3425:18)
#12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
#15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2573:19)
#16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#17     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#18     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
====================================================================================================
```

**Comment by spydon** [comment]
The example is updated for `main`, you have to run the example for the version that you are using:
https://github.com/flame-engine/flame/tree/1.0.0/packages/flame/example (for 1.0.0)

**Comment by YohanWadia** [comment]
I am not able to select 1.0.0 ... its as if that repo isnt available. When I use the drop down it isnt present... neither does the search show anything. May be you have extra privileges to see that repo... but I cant. I've tried from both my accounts.

If it wasnt for your link... I would have never been able to get there.
post that the game never threw an error

**Comment by spydon** [comment]
You are running thr example from `main`, select the `1.0.0` tag and use that example instead. The `main` branch has gesture festures that aren't available on `1.0.0` yet.

**Comment by spydon** [comment]
I can see the full list of tags even when not being logged in and using incognito mode, are you sure that you are looking in the tags list and not the branch list?
![image](https://user-images.githubusercontent.com/744771/147496930-0044e44f-0afd-42a5-af25-8f999eff7700.png)
You can also just go here to see the tags:
https://github.com/flame-engine/flame/tags

**Comment by YohanWadia** [comment]
@spydon ... thanks for getting back.
Yeah now I know what you mean... It was an error on my end.
Im able to see them clearly when I check under tags... thanks.
Sorry about the confusion.
thanks again ;-)
