### ISSUE TITLE
Error loading assets from `assets/images`

### ISSUE THREAD

**Issue by Sanhajio** [flame-engine/flame#1301]
I am on ubuntu20.04
# Current bug behaviour
When I run the getting started example; I get this error:
```
~/development/flame/flame_getting_started$ flutter run
Running "flutter pub get" in flame_getting_started...              717ms
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             26.9s
This app is linked to the debug service: ws://127.0.0.1:42167/Jbher14s4q4=/ws
Debug service listening on ws://127.0.0.1:42167/Jbher14s4q4=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:42167/Jbher14s4q4=
Error while trying to load an asset: Failed to load asset at "assets/assets/images/Meow-Knight_Idle.png" (404)
Error: Unable to load asset: assets/images/Meow-Knight_Idle.png
    at Object.throw_ [as throw] (http://localhost:37801/dart_sdk.js:5063:11)
    at load (http://localhost:37801/packages/flutter/src/services/restoration.dart.lib.js:6181:38)
    at load.next (<anonymous>)
    at http://localhost:37801/dart_sdk.js:40192:33
    at _RootZone.runUnary (http://localhost:37801/dart_sdk.js:40062:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:37801/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:37801/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:37801/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:37801/dart_sdk.js:35437:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:37801/dart_sdk.js:35458:35)
    at Object._microtaskLoop (http://localhost:37801/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:37801/dart_sdk.js:40336:13)
    at http://localhost:37801/dart_sdk.js:35811:9
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:42167/Jbher14s4q4=
```
It's assets that is dupplicated twice
```
~/development/flame/flame_getting_started$ ls -R assets/
assets/:
images

assets/images:
Meow_Knight.aseprite      Meow-Knight_Attack_2.png  Meow-Knight_Attack_4.png  Meow-Knight_Dodge.png  Meow-Knight_Jump.png  Meow-Knight_Take_Damage.png
Meow-Knight_Attack_1.png  Meow-Knight_Attack_3.png  Meow-Knight_Death.png     Meow-Knight_Idle.png   Meow-Knight_Run.png
```
main.dart:
```
import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flame/input.dart';
import 'package:flutter/material.dart';

class MyCrate extends SpriteComponent {
  MyCrate() : super(size: Vector2.all(240));

  Future<void> onLoad() async {
    sprite = await Sprite.load('Meow-Knight_Idle.png');
    anchor = Anchor.center;
  }

  @override
  void onGameResize(Vector2 gameSize) {
    super.onGameResize(gameSize);
    position = gameSize/2;
  }
}

class MyGame extends FlameGame {
  @override
  Future<void> onLoad() async {
    await super.onLoad();
    add(MyCrate());
  }
}

main() {
  final myGame = MyGame();
  runApp(
      GameWidget(
          game: myGame,
      ),  
  );  
}

```

# Expected behaviour
default to using: `assets/images/Meow-Knight_Idle.png` instead of `assets/assets/images/Meow-Knight_Idle.png`

# More environment information
* Flame version: 1.0.0
* Platform affected: android, ios, web
* Platform version affected: all

# More information
I can PR this

**Comment by Sanhajio** [comment]
I guess I need to close this, since this is not happening anymore in flame main branch. :+1: It's fixed, I'll use the main branch for now.

**Comment by spydon** [comment]
This should work fine in the released versions too, are you sure you properly restarted the app after you added the assets?

**Comment by Sanhajio** [comment]
Yes, I did, Let me try that again, I'll look it up more. It seemed suspicious when I saw the error.
