### ISSUE TITLE
Illegal audio focus gain type 0 in FlameAudio.bgm.play

### ISSUE THREAD

**Issue by Cubel89** [flame-engine/flame#1820]
# Current bug behaviour
When trying to play an audio with FlameAudio.bgm.play (flame_audio: ^1.3.0) it shows me the following error:

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Unexpected error!, Illegal audio focus gain type 0, java.lang.IllegalArgumentException: Illegal audio focus gain type 0

Example:
```
FlameAudio.bgm.play('sound.wav', volume: 1.0);
```

# Expected behaviour
Until previous versions, it worked fine for me. At last, I realized that on iOS devices it did not play in a loop, but now on Android it shows me the error mentioned above

# Flutter doctor output
```
Flutter Doctor:
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.15.0-41-generic, locale es_ES.UTF-8)
    • Flutter version 3.0.1 at /home/cubel/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (hace 10 semanas), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /home/cubel/Android/Sdk
    • Platform android-TiramisuPrivacySandbox, build-tools 33.0.0-rc4
    • Java binary at: /snap/android-studio/123/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/123/android-studio
    • Flutter plugin version 68.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Ubuntu 20.04.4 LTS 5.15.0-41-generic
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0
```

# More environment information
```
	flame: ^1.2.1
  	flame_svg: ^1.4.0
  	flame_tiled: ^1.6.0
  	flame_audio: ^1.3.0
```

# Log information
```
V/MediaPlayer( 5400): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 5400): cleanDrmObj: mDrmObj=null mDrmSessionId=null
D/AudioPlayers( 5400): Unexpected error!
D/AudioPlayers( 5400): java.lang.IllegalArgumentException: Illegal audio focus gain type 0
D/AudioPlayers( 5400): 	at android.media.AudioFocusRequest$Builder.setFocusGain(AudioFocusRequest.java:405)
D/AudioPlayers( 5400): 	at android.media.AudioFocusRequest$Builder.<init>(AudioFocusRequest.java:373)
D/AudioPlayers( 5400): 	at xyz.luan.audioplayers.player.FocusManager.newRequestAudioFocus(FocusManager.kt:47)
D/AudioPlayers( 5400): 	at xyz.luan.audioplayers.player.FocusManager.maybeRequestAudioFocus(FocusManager.kt:25)
D/AudioPlayers( 5400): 	at xyz.luan.audioplayers.player.WrappedPlayer.play(WrappedPlayer.kt:157)
D/AudioPlayers( 5400): 	at xyz.luan.audioplayers.AudioplayersPlugin.handler(AudioplayersPlugin.kt:96)
D/AudioPlayers( 5400): 	at xyz.luan.audioplayers.AudioplayersPlugin.access$handler(AudioplayersPlugin.kt:23)
D/AudioPlayers( 5400): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:39)
D/AudioPlayers( 5400): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:39)
D/AudioPlayers( 5400): 	at xyz.luan.audioplayers.AudioplayersPlugin$safeCall$1.invokeSuspend(AudioplayersPlugin.kt:58)
D/AudioPlayers( 5400): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
D/AudioPlayers( 5400): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
D/AudioPlayers( 5400): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
D/AudioPlayers( 5400): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
D/AudioPlayers( 5400): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
D/AudioPlayers( 5400): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
D/AudioPlayers( 5400): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
D/AudioPlayers( 5400): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
E/flutter ( 5400): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Unexpected error!, Illegal audio focus gain type 0, java.lang.IllegalArgumentException: Illegal audio focus gain type 0
E/flutter ( 5400): 	at android.media.AudioFocusRequest$Builder.setFocusGain(AudioFocusRequest.java:405)
E/flutter ( 5400): 	at android.media.AudioFocusRequest$Builder.<init>(AudioFocusRequest.java:373)
E/flutter ( 5400): 	at xyz.luan.audioplayers.player.FocusManager.newRequestAudioFocus(FocusManager.kt:47)
E/flutter ( 5400): 	at xyz.luan.audioplayers.player.FocusManager.maybeRequestAudioFocus(FocusManager.kt:25)
E/flutter ( 5400): 	at xyz.luan.audioplayers.player.WrappedPlayer.play(WrappedPlayer.kt:157)
E/flutter ( 5400): 	at xyz.luan.audioplayers.AudioplayersPlugin.handler(AudioplayersPlugin.kt:96)
E/flutter ( 5400): 	at xyz.luan.audioplayers.AudioplayersPlugin.access$handler(AudioplayersPlugin.kt:23)
E/flutter ( 5400): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:39)
E/flutter ( 5400): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:39)
E/flutter ( 5400): 	at xyz.luan.audioplayers.AudioplayersPlugin$safeCall$1.invokeSuspend(AudioplayersPlugin.kt:58)
E/flutter ( 5400): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/flutter ( 5400): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/flutter ( 5400): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
E/flutter ( 5400): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
E/flutter ( 5400): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
E/flutter ( 5400): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E/flutter ( 5400): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
E/flutter ( 5400): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
E/flutter ( 5400): , null)
E/flutter ( 5400): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 5400): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 5400): <asynchronous suspension>
E/flutter ( 5400): #2      AudioPlayer.resume (package:audioplayers/src/audioplayer.dart:144:5)
E/flutter ( 5400): <asynchronous suspension>
E/flutter ( 5400): #3      Bgm.play (package:flame_audio/bgm.dart:62:5)
E/flutter ( 5400): <asynchronous suspension>
E/flutter ( 5400): 
```

**Comment by spydon** [comment]
Does this happen on all audio files that you try, or only this one?

**Comment by Cubel89** [comment]
In all the audios that have FlameAudio.bgm.play (which are two, I am applying one for the start music and the other as background music in the game). The rest of the audios work fine (audios for button presses, jumps, death, etc...).

**Comment by Cubel89** [comment]
From what I understand flame_audio works with audioplayers library. Would there be the possibility of being able to assign a manual playerId when assigning a sound? I think I remember that in previous versions, sometimes it would fail me because it reached an audios limit. But I think I remember that what I am telling you now, happened to me with the short audios.

**Comment by spydon** [comment]
And it also happens if you use your audio for jump for example with the bgm?

**Comment by spydon** [comment]
> From what I understand flame_audio works with audioplayers library. Would there be the possibility of being able to assign a manual playerId when assigning a sound? I think I remember that in previous versions, sometimes it would fail me because it reached an audios limit. But I think I remember that what I am telling you now, happened to me with the short audios.

For short audios that you play a lot you should use `AudioCache`, which is part of `flame_audio`.

**Comment by Cubel89** [comment]
> And it also happens if you use your audio for jump for example with the bgm?

No no, for small audios I use play ("FlameAudio.play('explosion.mp3')"), but previously I have cached everything as indicated in the documentation of version 1.1.0 (https://docs.flame-engine.org/1.1.0/flame_audio/audio.html)





> > From what I understand flame_audio works with audioplayers library. Would there be the possibility of being able to assign a manual playerId when assigning a sound? I think I remember that in previous versions, sometimes it would fail me because it reached an audios limit. But I think I remember that what I am telling you now, happened to me with the short audios.
> 
> For short audios that you play a lot you should use `AudioCache`, which is part of `flame_audio`.

I use this function FlameAudio.audioCache.loadAll(['explosion.mp3', 'music.mp3']) as the documentation indicates

**Comment by spydon** [comment]
> No no, for small audios I use play ("FlameAudio.play('explosion.mp3')"), but previously I have cached everything as indicated in the documentation of version 1.1.0 (https://docs.flame-engine.org/1.1.0/flame_audio/audio.html)

I mean if you use the `explosion.mp3` file but with `bgm`, just to see whether it could be a problem with the file format or something like that.

> I use this function FlameAudio.audioCache.loadAll(['explosion.mp3', 'music.mp3']) as the documentation indicates

Sorry typo, I meant `AudioPool`. But if it works for you just with `FlameAudio.play` then no need to change it.

**Comment by Cubel89** [comment]
If I have time this afternoon, or if not tomorrow, I'll prepare a mini-project where I replicate what I do, page 1 I put everything in cache, page 2 reproduces the content.

I haven't tried changing the bgm format. But I'll try it too. I have not tried it because the same thing happens to me with 2 different files. Both versions worked back but now the error appears in both.
