### ISSUE TITLE
The example app tapping does not work

### ISSUE THREAD

**Issue by carlchandev** [flame-engine/flame#221]
I tried creating a new flutter app and just copy the whole main file to my app.
I did not modify anything on main but whenever I tap on the screen, it throws

![image](https://user-images.githubusercontent.com/34772941/74624119-3a10cf80-5182-11ea-94f3-30bde91eedb7.png)

```flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following StateError was thrown while handling a gesture:
flutter: Bad state: Cannot add event after closing
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      HasWidgetsOverlay.addWidgetOverlay (package:flame/game/game.dart:90:34)
flutter: #3      ExampleGame.onTap (package:flappy_bird/main.dart:27:7)
flutter: #4      WidgetBuilder.build.<anonymous closure> (package:flame/game/widget_builder.dart:11:64)
flutter: #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
flutter: #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
flutter: #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
flutter: #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:470:9)
flutter: #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
flutter: #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
flutter: #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
flutter: #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
flutter: #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
flutter: #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
flutter: #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
flutter: #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
flutter: #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
flutter: #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
flutter: #23     _invoke1 (dart:ui/hooks.dart:274:10)
flutter: #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:183:5)
flutter: (elided 5 frames from dart:async)
flutter:
flutter: Handler: "onTap"
flutter: Recognizer:
flutter:   TapGestureRecognizer#c3929
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by carlchandev** [comment]
I think I posted on a wrong thread. Close it.
