### ISSUE TITLE
AudioPool is not working when play sounds multiple times

### ISSUE THREAD

**Issue by denghejun** [flame-engine/flame#2492]
```
flutter: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:178:5)
<asynchronous suspension>
#3      FlameAudio._preparePlayer (package:flame_audio/flame_audio.dart:23:5)
```

**Comment by spydon** [comment]
@denghejun can you provide some more information about how to reproduce this?
