### ISSUE TITLE
AVPlayerItem fails on setSourceUrl after playing for about 2 or 3 minutes when running on iOS device

### ISSUE THREAD

**Issue by antoniobrandao** [flame-engine/flame#2542]
I'm writing an app that plays a sound repeatedly, and it works but fails after a couple of minutes.

The error occurs on the device, not on the simulator. Happens in both the debug mode as well as in the release archive after submitting to TestFlight.

Device I'm using is iPhone 13 Pro

# Current bug behavior
The app crashes after 2 or 3 minutes (stack trace below)

# Expected behavior
That it would keep playing as it plays when it starts.

# Steps to reproduce
I created a ready-to-test Flutter app in this repo:
https://github.com/antoniobrandao/flutter-timer-test

Run it using an iPhone to preview & reproduce the error.

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-PT)
    • Flutter version 3.10.1 on channel stable at /Users/antoniobrandao/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (5 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/antoniobrandao/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.65.20230510

[✓] Connected device (2 available)
    • Antonio’s iPhone (mobile) • 00008110-000209841E83801E • ios          • iOS 16.1 20B82
    • macOS (desktop)           • macos                     • darwin-arm64 • macOS 13.3.1 22E772610a darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

# Environment information

* flame_audio: ^2.0.2
* Platform affected: ios (didn't try others)
* Platform version affected: ios 16.1

# Log information

```
    [ +723 ms] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl, null, null)
    [        ] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
    [        ] #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
    [        ] <asynchronous suspension>
    [        ] #2      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:178:5)
    [        ] <asynchronous suspension>
    [        ] #3      FlameAudio._preparePlayer (package:flame_audio/flame_audio.dart:23:5)
    [        ] <asynchronous suspension>
```

# More information
I've tried this with MP3, AIFF and WAV files, error happens the same.

I also notice higher delays between beeps when the crash is about to happen.

**Comment by spydon** [comment]
When using repetitive sounds like this it's usually better to use `AudioPool` which is another class from AudioPlayers (the library that flame_audio bridges to).

**Comment by spydon** [comment]
This should be fixed in a newer version of AudioPlayers
