### ISSUE TITLE
Test Github action get killed prematurely

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#2691]
# Current bug behavior
The test Github action get killed prematurely.

# Expected behavior
It runs until the end.

# Steps to reproduce
50% of the time the test pipeline step gets killed.

# Logs
```
 ##[debug]Re-evaluate condition on job cancellation for step: 'run'.
##[debug]Skip Re-evaluate condition on runner shutdown.
 PASS  packages/flame_jenny/jenny/test/structure/expressions/operators/negate_test.dart
 STOP  packages/flame_forge2d/test/body_component_test.dart
 STOP  packages/flame_noise/test/perlin_noise_effect_controller_test.dart
 STOP  packages/flame_tiled/test/tiled_test.dart
And 12 more.

Test Suites: 35 passed, 35 total
Tests:       271 passed, 1 skipped, 272 total
Time:        4 minutes 5 seconds
##[debug]Re-evaluate condition on job cancellation for step: 'Run bluefireteam/spec-action@main'.
##[debug]Skip Re-evaluate condition on runner shutdown.
Test run was interrupted.
Error: The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
##[debug]   at System.Threading.CancellationToken.ThrowOperationCanceledException()
##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.ScriptHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.Handlers.CompositeActionHandler.RunStepAsync(IStep step)
##[debug]Finished: run
##[debug]Finishing: Run bluefireteam/spec-action@main
```

# More info
I read something about this only happening on `ubuntu-latest` and not the older one, could also be worth checking if the action is running out of RAM or something like that.

**Comment by spydon** [comment]
Might be solved with #2698
