### ISSUE TITLE
SpriteAnimationWidget bug with cleared cache

### ISSUE THREAD

**Issue by imaNNeo** [flame-engine/flame#2841]
# Current bug behavior
When you have a `SpriteAnimationWidget` (which loads a sprite from the `assets/images`) and call `Flame.images.clearCache();`, it throws an error in the new page
```
The following assertion was thrown during paint():
'dart:ui/painting.dart': Failed assertion: line 6011 pos 12: '<optimized out>': is not true.
```

# Expected behavior
I expect it to cache the image again (when it doesn't exist in the cache)

# Steps to reproduce
1. Create two separate pages
2. Add SpriteAnimationWidget which loads a specific sprite from `assets/images` in both pages
3. Call `Flame.images.clearCache();` in the page1.onDispose();
4. Add a button in page1 which opens page2
5. Click on the button in page1 to go to the page2
6. You will see the exception in our logs

Check this [reproducible code in zapp](https://zapp.run/edit/flame-zq1m069dq1n0?entry=lib/main.dart&file=pubspec.yaml)

# Flutter doctor output
```
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.13.9 on channel stable at /Users/neo/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (11 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/neo/Library/Android/sdk
    • Platform android-34-ext8, build-tools 34.0.0
    • ANDROID_HOME = /Users/neo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/neo/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Users/neo/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.1.4)
    • IntelliJ at /Users/neo/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/231.9225.16/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /Users/neo/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/232.8660.185/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/neo/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9225.16/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Users/neo/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.8660.185/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.84.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.105

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

# More environment information
```
* Flame version: 1.10.1
* Platform tested: macos, iPhone
```

# Log information

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
'dart:ui/painting.dart': Failed assertion: line 6011 pos 12: '<optimized out>': is not true.

The relevant error-causing widget was: 
  SpriteAnimationWidget SpriteAnimationWidget:file:///Users/neo/IdeaProjects/flame_sprite_animation_widget_bug/lib/main.dart:97:44
When the exception was thrown, this was the stack: 
#2      _NativeCanvas.drawImageRect (dart:ui/painting.dart:6011:12)
#3      Sprite.render (package:flame/src/sprite.dart:121:12)
#4      SpritePainter.paint (package:flame/src/widgets/sprite_painter.dart:36:15)
#5      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:573:13)
#6      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:615:7)
#7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#9      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#12     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2875:15)
#13     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1040:7)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#16     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#19     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2875:15)
#20     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:410:5)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#24     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:664:11)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#27     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#28     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2049:15)
#29     PaintingContext.pushClipRRect (package:flutter/src/rendering/object.dart:561:14)
#30     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:2036:21)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#33     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:252:13)
#36     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:129:13)
#37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:3155:7)
#38     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:168:11)
#39     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:5)
#40     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1144:31)
#41     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:496:19)
#42     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#43     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#44     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#45     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#46     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#47     _invoke (dart:ui/hooks.dart:170:13)
#48     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#49     _drawFrame (dart:ui/hooks.dart:140:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#87fbd
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=32.0, h=32.0)
...  size: Size(32.0, 32.0)
...  painter: SpritePainter#f7a3e()
RenderObject: RenderCustomPaint#87fbd
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=32.0, h=32.0)
  size: Size(32.0, 32.0)
  painter: SpritePainter#f7a3e()
====================================================================================================
```

**Comment by spydon** [comment]
Could you share a link to a repository with the code instead?
Zapp doesn't support the version of Flutter that Flame requires.

**Comment by imaNNeo** [comment]
Sure!
This is [the repository](https://github.com/imaNNeo/flame_sprite_animation_widget_bug).

**Comment by spydon** [comment]
Ah right, this is not Flame's fault, this is just how the lifecycle of the widgets work:
https://stackoverflow.com/questions/67741637/how-to-ensure-dispose-will-be-called-before-new-widgets-initstate

**Comment by spydon** [comment]
A work-around could be to cache the image in the state instead of in the global image cache.

**Comment by imaNNeo** [comment]
Oh, you're right. 
So I will close this issue.
Thanks for your hint!
