### ISSUE TITLE
Flame + Forge2D + Riverpod == broken?

### ISSUE THREAD

**Issue by domesticmouse** [flame-engine/flame#3111]
### What happened?

I'm attempting to use `Forge2DGame with RiverpodGameMixin` but I'm seeing a callstack on initialization. 

### What do you expect?

I'd like the sample to run. =)

### How can we reproduce this?

Sample code:

```dart
import 'package:flame/components.dart';
import 'package:flame/events.dart';
import 'package:flame/extensions.dart';
import 'package:flame/game.dart';
import 'package:flame_forge2d/flame_forge2d.dart';
import 'package:flame_riverpod/flame_riverpod.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(
    ProviderScope(
      child: GameWidget.controlled(
        gameFactory: Forge2DExample.new,
      ),
    ),
  );
}

class Forge2DExample extends Forge2DGame with RiverpodGameMixin {
  @override
  Future<void> onLoad() async {
    await super.onLoad();

    final size = camera.viewport.size;

    camera.viewport.add(
      FpsTextComponent(
        anchor: Anchor.bottomRight,
        position: size - Vector2(10, 10),
      ),
    );
    world.add(Ball());
    await world.addAll(createBoundaries());
  }

  List<Component> createBoundaries() {
    final visibleRect = camera.visibleWorldRect;
    final topLeft = visibleRect.topLeft.toVector2();
    final topRight = visibleRect.topRight.toVector2();
    final bottomRight = visibleRect.bottomRight.toVector2();
    final bottomLeft = visibleRect.bottomLeft.toVector2();

    return [
      Wall(topLeft, topRight),
      Wall(topRight, bottomRight),
      Wall(bottomLeft, bottomRight),
      Wall(topLeft, bottomLeft),
    ];
  }
}

class Ball extends BodyComponent with TapCallbacks {
  Ball({Vector2? initialPosition})
      : super(
          fixtureDefs: [
            FixtureDef(
              CircleShape()..radius = 5,
              restitution: 0.8,
              friction: 0.4,
            ),
          ],
          bodyDef: BodyDef(
            angularDamping: 0.8,
            position: initialPosition ?? Vector2.zero(),
            type: BodyType.dynamic,
          ),
        );

  @override
  void onTapDown(event) {
    body.applyLinearImpulse(Vector2.random() * 5000);
  }
}

class Wall extends BodyComponent {
  final Vector2 _start;
  final Vector2 _end;

  Wall(this._start, this._end);

  @override
  Body createBody() {
    final shape = EdgeShape()..set(_start, _end);
    final fixtureDef = FixtureDef(shape, friction: 0.3);
    final bodyDef = BodyDef(
      position: Vector2.zero(),
    );

    return world.createBody(bodyDef)..createFixture(fixtureDef);
  }
}
```

### What steps should take to fix this?

I'm guessing I'm holding it wrong. Plz help!

### Relevant log output

```shell
Connecting to VM Service at ws://127.0.0.1:59167/qB2Ma-mQU2U=/ws
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      RiverpodGameMixin.onMount.<anonymous closure> (package:flame_riverpod/src/consumer.dart:149:16)
#1      _RootZone.run (dart:async/zone.dart:1655:54)
#2      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:205:18)
#3      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:808:39)
#4      Future._propagateToListeners (dart:async/future_impl.dart:864:11)
#5      Future._completeWithValue (dart:async/future_impl.dart:643:5)
#6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:713:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

### Execute in a terminal and put output into the code block below

```console
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en)
    • Flutter version 3.19.5 on channel stable at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 300451adae (4 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] IntelliJ IDEA Community Edition (version 2023.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13135.65

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 123.0.6312.87

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Affected platforms

macOS

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
Hey @domesticmouse!
You need to use the `RiverpodAwareGameWidget` instead of the normal `GameWidget` when using `flame_riverpod`.
