### ISSUE TITLE
bug: Unexpected concurrent modification

### ISSUE THREAD

**Issue by erickzanardo** [flame-engine/flame#3416]
### What happened?

Flame breaks with concurrent modification when there are too many things happening at the same time and events happen asynchronously. 

I believe this is happening because components are being added after their parent have been removed, and since there are too many things happening at the same time, the add/remove queue were not able to be processed before a frame finished. This is just a guess though, I am not 100% sure this is the case.

### What do you expect?

Flame doesn't break

### How can we reproduce this?

https://github.com/flame-engine/flame_concurrent_mod_error

Run the project above, smash space key and see the error happening.

If the following code in the `_animate` method get uncommented, the error cease to happen:

```
    //if (_beingRemoved) {
    //  return;
    //}
```

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

All

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment]
Can you add the full stacktrace?

**Comment by itsdax** [comment]
Not the author, but I'm seeing a similar issue on flame: ^1.19.0

```
[✓] Flutter (Channel beta, 3.27.0-0.2.pre, on macOS 15.1 24B2083 darwin-arm64, locale en-US)
    • Flutter version 3.27.0-0.2.pre on channel beta at /Users/macbook/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fc011960a2 (6 weeks ago), 2024-11-14 12:19:18 -0800
    • Engine revision 397deba30f
    • Dart version 3.6.0 (build 3.6.0-334.4.beta)
    • DevTools version 2.40.1
```

```
======== Exception caught by scheduler library =====================================================
The following ConcurrentModificationError was thrown during a scheduler callback:
Concurrent modification during iteration: _Set len:7.

When the exception was thrown, this was the stack: 
#0      _CompactIterator.moveNext (dart:_compact_hash:806:7)
#1      _OrderedSetIterator.moveNext (package:ordered_set/ordered_set.dart:197:25)
#2      Iterable.forEach (dart:core/iterable.dart:347:23)
#3      Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#4      Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:527:33)
#5      Iterable.forEach (dart:core/iterable.dart:347:35)
#6      Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#7      Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:527:33)
#8      Iterable.forEach (dart:core/iterable.dart:347:35)
#9      Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#10     Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:527:33)
#11     Iterable.forEach (dart:core/iterable.dart:347:35)
#12     Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#13     Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:527:33)
#14     Iterable.forEach (dart:core/iterable.dart:347:35)
#15     Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#16     HasTimeScale.updateTree (package:flame/src/components/mixins/has_time_scale.dart:35:11)
#17     Route.updateTree (package:flame/src/components/route.dart:176:13)
#18     Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:527:33)
#19     Iterable.forEach (dart:core/iterable.dart:347:35)
#20     Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#21     Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:527:33)
#22     Iterable.forEach (dart:core/iterable.dart:347:35)
#23     Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#24     FlameGame.updateTree (package:flame/src/game/flame_game.dart:163:17)
#25     FlameGame.update (package:flame/src/game/flame_game.dart:152:7)
#26     GameRenderBox.gameLoopCallback (package:flame/src/game/game_render_box.dart:121:10)
#27     GameLoop._tick (package:flame/src/game/game_loop.dart:46:13)
#28     Ticker._tick (package:flutter/src/scheduler/ticker.dart:275:12)
#29     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#30     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1240:11)
#31     _LinkedHashMapMixin.forEach (dart:_compact_hash:726:13)
#32     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1238:17)
#33     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1155:5)
#34     _invoke1 (dart:ui/hooks.dart:328:13)
#35     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:405:5)
#36     _beginFrame (dart:ui/hooks.dart:272:31)
```

**Comment by spydon** [comment]
Which is the last version that this works in?
This must be one of the recent changes either in Flame or ordered_set, wdyt @luanpotter?

**Comment by itsdax** [comment]
For the stack trace I've observed, I believe it was always an issue but albeit quite rare. My app has always been on `^1.19.0` and the effect usually surfaces in an App-Not-Responding scenario.

**Comment by spydon** [comment]
@itsdax you could depend on `main` to try out the changes before a release, or do you want to make a release to your beta users to try it out? If so I can make a new Flame release now.

**Comment by itsdax** [comment]
Ah dang - using main but it looks like the problem persists

```
======== Exception caught by scheduler library =====================================================
The following ConcurrentModificationError was thrown during a scheduler callback:
Concurrent modification during iteration: _Set len:5.

When the exception was thrown, this was the stack: 
#0      _CompactIterator.moveNext (dart:_compact_hash:806:7)
#1      _OrderedSetIterator.moveNext (package:ordered_set/ordered_set.dart:197:25)
#2      Iterable.forEach (dart:core/iterable.dart:347:23)
#3      Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#4      Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:527:33)
#5      Iterable.forEach (dart:core/iterable.dart:347:35)
#6      Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#7      Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:527:33)
#8      Iterable.forEach (dart:core/iterable.dart:347:35)
#9      Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#10     Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:527:33)
#11     Iterable.forEach (dart:core/iterable.dart:347:35)
#12     Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#13     Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:527:33)
#14     Iterable.forEach (dart:core/iterable.dart:347:35)
#15     Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#16     HasTimeScale.updateTree (package:flame/src/components/mixins/has_time_scale.dart:35:11)
#17     Route.updateTree (package:flame/src/components/router/route.dart:176:13)
#18     Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:527:33)
#19     Iterable.forEach (dart:core/iterable.dart:347:35)
#20     Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#21     Component.updateTree.<anonymous closure> (package:flame/src/components/core/component.dart:527:33)
#22     Iterable.forEach (dart:core/iterable.dart:347:35)
#23     Component.updateTree (package:flame/src/components/core/component.dart:527:16)
#24     FlameGame.updateTree (package:flame/src/game/flame_game.dart:163:17)
#25     FlameGame.update (package:flame/src/game/flame_game.dart:152:7)
#26     GameRenderBox.gameLoopCallback (package:flame/src/game/game_render_box.dart:121:10)
#27     GameLoop._tick (package:flame/src/game/game_loop.dart:46:13)
#28     Ticker._tick (package:flutter/src/scheduler/ticker.dart:275:12)
#29     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#30     SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1240:11)
#31     _LinkedHashMapMixin.forEach (dart:_compact_hash:726:13)
#32     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1238:17)
#33     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1155:5)
#34     _invoke1 (dart:ui/hooks.dart:328:13)
#35     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:405:5)
#36     _beginFrame (dart:ui/hooks.dart:272:31)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack: 
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:611:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:291:46)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:197:7)
#5      GameLoop.start (package:flame/src/game/game_loop.dart:54:15)
#6      GameRenderBox._attachGame (package:flame/src/game/game_render_box.dart:97:16)
#7      GameRenderBox.attach (package:flame/src/game/game_render_box.dart:88:5)
#8      RenderObject.adoptChild (package:flutter/src/rendering/object.dart:1860:13)
#9      RenderObjectWithChildMixin.child= (package:flutter/src/rendering/object.dart:4157:7)
#10     SingleChildRenderObjectElement.insertRenderObjectChild (package:flutter/src/widgets/framework.dart:6929:18)
#11     RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:6746:35)
#12     RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6611:5)
...     Normal element mounting (15 frames)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4480:16)
#28     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7049:36)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3963:18)
#30     Element.updateChildren (package:flutter/src/widgets/framework.dart:4150:32)
#31     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7074:17)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5656:16)
#34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5794:11)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:5347:7)
#36     StatefulElement.update (package:flutter/src/widgets/framework.dart:5817:5)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#38     _LayoutBuilderElement._rebuildWithConstraints.updateChildCallback (package:flutter/src/widgets/layout_builder.dart:215:18)
#39     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3038:19)
#40     _LayoutBuilderElement._rebuildWithConstraints (package:flutter/src/widgets/layout_builder.dart:239:12)
#41     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2738:59)
#42     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1108:15)
#43     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2738:14)
#44     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:286:5)
#45     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:377:5)
#46     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2465:7)
#47     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1062:18)
#48     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1075:15)
#49     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:609:23)
#50     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1178:13)
#51     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475:5)
#52     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#53     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#54     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#55     _invoke (dart:ui/hooks.dart:312:13)
#56     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:427:5)
#57     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _FrameCallbackEntry)
```

**Comment by itsdax** [comment]
I have a class that surfaces this behavior at a much more frequent rate, which is pasted below:

I have a high suspicion that it may be due to `_spawnBurst` being called inside `update()`, which calls `parent?.add(burst);`. Is it problematic to have add/remove inside `update()`?



```
import 'dart:math';
import 'dart:ui';

import 'package:flame/components.dart';
import 'package:flame/particles.dart';
import 'package:flutter/material.dart';

ParticleSystemComponent createFireBurst({
  required Vector2 position,
  required int numberOfParticles,
  double lifespan = 1.0,
}) {
  return ParticleSystemComponent(
    position: position,
    particle: Particle.generate(
      count: numberOfParticles,
      generator: (i) => _fireParticle(lifespan: lifespan),
    ),
  );
}

/// A single "fire" particle composed of two layers.
Particle _fireParticle({required double lifespan}) {
  const double xRange = 100;
  final vx = Random().nextDouble() * xRange - xRange / 2; // e.g. -20..+20
  final vy = -(Random().nextDouble() * 50 + 25); // moves upward

  // Inner core
  final core = AcceleratedParticle(
    lifespan: lifespan,
    speed: Vector2(vx, vy),
    child: ComputedParticle(
      lifespan: lifespan,
      renderer: (canvas, particle) {
        final t = particle.progress;
        final color = Color.lerp(
          Colors.yellow.withOpacity(0.5),
          Colors.orange.withOpacity(0.0),
          t,
        )!;
        final radius = lerpDouble(2.0, 0.0, t)!;
        final paint = Paint()..color = color;
        canvas.drawCircle(Offset.zero, radius, paint);
      },
    ),
  );

  // Outer flame
  final outer = AcceleratedParticle(
    lifespan: lifespan,
    speed: Vector2(vx, vy),
    child: ComputedParticle(
      lifespan: lifespan,
      renderer: (canvas, particle) {
        final t = particle.progress;
        final color = Color.lerp(
          Colors.orange.withOpacity(1.0),
          Colors.red.withOpacity(0.0),
          t,
        )!;
        final radius = lerpDouble(4.0, 2.0, t)!;
        final paint = Paint()..color = color;
        canvas.drawCircle(Offset.zero, radius, paint);
      },
    ),
  );

  return ComposedParticle(children: [core, outer]);
}

class FlameSpawnerComponent extends PositionComponent {
  /// How long the effect should last in total.
  final double effectDuration;

  /// Interval in seconds between bursts (e.g., spawn flames every 0.3s).
  final double spawnInterval;

  /// Number of flame particles per burst (tweak for density).
  final int burstParticleCount;

  /// How long each batch of particles lives (from your createFireBurst).
  final double burstLifespan;

  double _elapsed = 0.0;
  double _acc = 0.0;

  FlameSpawnerComponent({
    required Vector2 position,
    required this.effectDuration,
    this.spawnInterval = 0.3,
    this.burstParticleCount = 15,
    this.burstLifespan = 1.0,
  }) {
    this.position = position;
  }

  @override
  void update(double dt) {
    super.update(dt);

    _elapsed += dt;

    // Stop spawner after effectDuration
    if (_elapsed >= effectDuration) {
      removeFromParent();
      return;
    }

    // Accumulate time to see if it's time for another burst
    _acc += dt;
    if (_acc >= spawnInterval) {
      _acc -= spawnInterval;
      _spawnBurst();
    }
  }

  void _spawnBurst() {
    // Create a new burst at this spawner's position
    final burst = createFireBurst(
      position: position.clone(),
      numberOfParticles: burstParticleCount,
      lifespan: burstLifespan,
    );

    // If this spawner is attached to a parent (like the fighter),
    // we add the burst to the same parent so it appears at the
    // correct location in the scene.
    parent?.add(burst);
  }
}

```

**Comment by spydon** [comment]
>>> I have a high suspicion that it may be due to _spawnBurst being called inside update(), which calls parent?.add(burst);. Is it problematic to have add/remove inside update()?

It shouldn't be, but it clearly looks like we've done something so that it is. Could you try to pin `ordered_set` to 5.0.3 and 6.0.1?

**Comment by itsdax** [comment]
Will do!

My project uses `[6.1.1](https://pub.dev/packages/ordered_set/versions/6.1.1)`

Testing with 6.0.1, the issue still persists.

Not able to try 5.0.3 due to it being a bit too old for my other deps:
```
Error (Xcode): ../../.pub-cache/git/flame-994e098bd699a30aa13aed65f2bd0ab7254ad779/packages/flame/lib/src/components/core/component_set.dart:92:15: Error: The return type of the method 'ComponentSet.query' is 'Iterable<C>', which does not match the return type, 'List<C>', of the overridden method, 'QueryableOrderedSet.query'.
```
