### ISSUE TITLE
After adding flame in pubspec.yaml flutter run cannot work on ios, No `Podfile' found in the project directory

### ISSUE THREAD

**Issue by jackyanjiaqi** [flame-engine/flame#344]
Here is my console error output:
```
zhuofanerdeMBP:flutter_app 2 zhuofaner$ flutter run
 
Launching lib/main.dart on iPhone 8 in debug mode...
Running pod install...                                              0.8s
CocoaPods' output:
↳
    [!] No `Podfile' found in the project directory.

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:151:in `verify_podfile_exists!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:46:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 8.
```

**Comment by jackyanjiaqi** [comment]
I put the project under a Chinese named dir,fixed by change to another english name.
