### ISSUE TITLE
Tiled Example broken?

### ISSUE THREAD

**Issue by Flavsditz** [flame-engine/flame#345]
I have been trying a couple of the examples and a lot of them don't work on their current form.

One example which I was really trying to make it work is the Tiled example. It does throw the following error stack:

```
E/flutter (23845): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (23845): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (23845): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (23845): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
E/flutter (23845): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
E/flutter (23845): #2      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:219:15)
E/flutter (23845): #3      Images._fetchToMemory (package:flame/images.dart:44:46)
E/flutter (23845): #4      Images.load (package:flame/images.dart:25:37)
E/flutter (23845): #5      main (package:littlemancomputer/main.dart:12:16)
E/flutter (23845): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter (23845): #7      _rootRun (dart:async/zone.dart:1184:13)
E/flutter (23845): #8      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23845): #9      _runZoned (dart:async/zone.dart:1619:10)
E/flutter (23845): #10     runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter (23845): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter (23845): #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (23845): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

From what I can see the problem is that the `TileGame` class tries to use the TiledComponent which works with Futures and that is where everything starts to come down...

I read somewhere that some recent changes to Flutter made some things break in Flame, however I thought that the examples on this repo should be up-to-date.

Can anyone help? If I do understand the problem I can happily fix the examples on the repo. Just my know-how of flame is not big enough for it.

Cheers

Some infos:

```
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)

Flame version: 0.21.0
```

**Comment by erickzanardo** [comment]
A lot of the examples are a little old, and were made before a breaking change was introduced on Flutter, we try to fix them, but there is a lot of example and some are forgotten,
the fix is pretty easy though, just add this line first thing on the main method:

```dart
WidgetsFlutterBinding.ensureInitialized();
```

**Comment by Flavsditz** [comment]
That sounds good!
If it works I'll close this issue and work on a pull request as thanks ;)

**Comment by Flavsditz** [comment]
Just created a pull request! (Pull Request #346)
