### ISSUE TITLE
Android SDK file not found

### ISSUE THREAD

**Issue by jefrisingh** [flame-engine/flame#590]
## Description

I did wrote simple game with only background image, but unable to run :disappointed: 

## Development environment

Flame version: ^0.28.0

Flutter doctor:

```
jefri@JEFRI:~$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Linux, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ The lzma development library is required for Linux development.
      It is likely available from your distribution (e.g.: apt install
      liblzma-dev)
[!] Android Studio (not installed)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.

```

## Runtime

This issue is related to running on which platform? (Select all that apply)

 - [x] Android :android:
 - [ ] iOS :apple:
 - [x] Web :browser:

## Minimal reproducible code (Required for bugs)

Below is the total code, but unable to run :(

```
void main() {
  runApp(screenManager.widget);
}

ScreenManager screenManager = ScreenManager();
class ScreenManager extends Game{
  Function _fn;
  Size size = Size(0,0);
  ScreenManager(){
    _fn = _init;
  }

  BaseWidget _mainScreen;

  @override
  void resize(Size size) {
    //super.resize(size);
    this.size = size;
    _mainScreen?.resize(size);
  }
  @override
  void render(Canvas canvas) {
    _mainScreen?.render(canvas);
  }

  @override
  void update(double t) {
    _fn();
  }

  void _init(){
    _fn = _update;
    _mainScreen = new MainScreen();
  }

  void _update(){
    _mainScreen?.update();
  }

}

abstract class BaseWidget{
  void resize(Size size);
  void render(Canvas canvas);
  void update();
}


class MainScreen extends BaseWidget{
  Background _background;

  MainScreen(){
    _background = Background('background.png');
  }
  @override
  void render(Canvas canvas) {
    _background.render(canvas);
  }

  @override
  void resize(Size size) {
    _background.resize(size);
  }

  @override
  void update() {
    _background.update();
  }
}

```

Here is the output in console :

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performResize():
The GameRenderBox class does not implement "computeDryLayout".


If you are not writing your own RenderBox subclass, then this is not
your fault. Contact support: https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#0      RenderBox.debugCannotComputeDryLayout.<anonymous closure> (package:flutter/src/rendering/box.dart:1901:9)
#1      RenderBox.debugCannotComputeDryLayout (package:flutter/src/rendering/box.dart:1905:6)
#2      RenderBox.computeDryLayout (package:flutter/src/rendering/box.dart:1861:12)
#3      RenderBox.performResize (package:flutter/src/rendering/box.dart:2324:12)
#4      GameRenderBox.performResize (package:flame/game/game_render_box.dart:26:11)
...
The following RenderObject was being processed when the exception was fired: GameRenderBox#3dbb9 NEEDS-LAYOUT NEEDS-PAINT
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=485.4, h=814.8)
...  size: MISSING
RenderObject: GameRenderBox#3dbb9 NEEDS-LAYOUT NEEDS-PAINT
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=485.4, h=814.8)
  size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox did not set its size during layout.
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: GameRenderBox#3dbb9 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1923 pos 12: 'hasSize'
The relevant error-causing widget was: 
  EmbeddedGameWidget file:///home/jefri/.pub-cache/hosted/pub.dartlang.org/flame-0.28.0/lib/game/widget_builder.dart:230:16
The following RenderObject was being processed when the exception was fired: RenderConstrainedBox#ff90e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=485.4, h=814.8)
  size: MISSING
  additionalConstraints: BoxConstraints(biggest)
  child: GameRenderBox#3dbb9 NEEDS-PAINT
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=485.4, h=814.8)
    size: MISSING
RenderObject: RenderConstrainedBox#ff90e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=485.4, h=814.8)
  size: MISSING
  additionalConstraints: BoxConstraints(biggest)
  child: GameRenderBox#3dbb9 NEEDS-PAINT
    parentData: <none> (can use size)
    constraints: BoxConstraints(w=485.4, h=814.8)
    size: MISSING
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: RenderConstrainedBox#ff90e NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1923 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Container file:///home/jefri/.pub-cache/hosted/pub.dartlang.org/flame-0.28.0/lib/game/widget_builder.dart:226:21
====================================================================================================

======== Exception caught by rendering library =====================================================
RenderBox was not laid out: _RenderColoredBox#50d99
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1923 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Container file:///home/jefri/.pub-cache/hosted/pub.dartlang.org/flame-0.28.0/lib/game/widget_builder.dart:226:21
====================================================================================================

```

**Comment by spydon** [comment]
This is not in Flutter stable yet unfortunately, #552 is the PR with the fix on it.
We will most likely release `1.0.0-rc4` later today including that fix.
