### ISSUE TITLE
HasGameRef "Cannot find reference in the component tree"

### ISSUE THREAD

**Issue by ufrshubham** [flame-engine/flame#967]
# Current bug behaviour
When I try to resize the game window, components with HasGameRef are not able to find the FlameGame reference and a `StateError` is thrown from `gameRef` getter of `HasGameRef`.

# Expected behaviour
As this was working fine in rc13, I expect it to work the same in rc14 as well.

# Steps to reproduce
Following is a sample code which should be enough to reproduce this issue.  Just run it on Windows platform and try to resize the game window.
```dart
import 'package:flame/components.dart';
import 'package:flame/game.dart';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

final MyGame myGame = MyGame();

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: GameWidget(
        game: myGame,
      ),
    );
  }
}

class MyGame extends FlameGame {
  @override
  Future<void>? onLoad() async {
    final player = Player();
    add(player);
    return super.onLoad();
  }
}

class Player extends PositionComponent with HasGameRef<MyGame> {
  @override
  void update(double dt) {
    if (gameRef.camera.shaking) { // Fails at this line.
      print('Shaking');
    }
    super.update(dt);
  }
}
```

# Flutter doctor output
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
[!] Android Studio (not installed)
[√] VS Code (version 1.60.1)
[√] Connected device (3 available)

! Doctor found issues in 2 categories.
```

# More environment information
* Flame version: 1.0.0-releasecandidate.14
* Platform affected: Windows 10 (haven't tested on others yet)
* Platform version affected: 21H1

# Log information
<details>
<summary>Log</summary>
<p>

```
════════ Exception caught by scheduler library ═════════════════════════════════
The following StateError was thrown during a scheduler callback:
Bad state: Cannot find reference MyGame in the component tree

When the exception was thrown, this was the stack
#0      HasGameRef.gameRef
package:flame/…/mixins/has_game_ref.dart:21
#1      Player.update
package:bug_hunt/main.dart:42
#2      Component.update.<anonymous closure>
package:flame/…/components/component.dart:131
#3      IterableMixin.forEach (dart:collection/iterable.dart:45:35)
#4      Component.update
package:flame/…/components/component.dart:131
#5      FlameGame.update
package:flame/…/game/flame_game.dart:120
#6      GameRenderBox.gameLoopCallback
package:flame/…/game/game_render_box.dart:62
#7      GameLoop._tick
package:flame/…/game/game_loop.dart:14
#8      Ticker._tick
package:flutter/…/scheduler/ticker.dart:238
#9      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1143
#10     SchedulerBinding.handleBeginFrame.<anonymous closure>
package:flutter/…/scheduler/binding.dart:1056
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#12     SchedulerBinding.handleBeginFrame
package:flutter/…/scheduler/binding.dart:1054
#13     SchedulerBinding._handleBeginFrame
package:flutter/…/scheduler/binding.dart:975
#17     _invoke1 (dart:ui/hooks.dart:185:10)
#18     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:248:5)
#19     _beginFrame (dart:ui/hooks.dart:116:31)
(elided 3 frames from dart:async)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack
```

</p>
</details> 

# More information
Same code (with obvious minor changes) works in `1.0.0-releasecandidate.13`.
<details>
<summary>Working example in rc13</summary>
<p>

```dart
public class Order
import 'package:flame/components.dart';
import 'package:flame/game.dart';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

final MyGame myGame = MyGame();

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: GameWidget(
        game: myGame,
      ),
    );
  }
}

class MyGame extends BaseGame {
  @override
  Future<void> onLoad() async {
    final player = Player();
    add(player);

    return super.onLoad();
  }
}

class Player extends PositionComponent with HasGameRef<MyGame> {
  @override
  void update(double dt) {
    if (gameRef.camera.shaking) {
      print('Shaking');
    }
    super.update(dt);
  }
}
```

</p>
</details>

**Comment by luanpotter** [comment]
Fixed by https://github.com/flame-engine/flame/pull/987
